# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/OneDrive - HKUST Connect/Lab/OFDM_FPGA_VLC_Implementation/Receiver/prj/receiver_prj/receiver_prj.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
# IP: The module: 'udp_rx_ram_8_2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive - HKUST Connect/Lab/OFDM_FPGA_VLC_Implementation/Receiver/prj/receiver_prj/receiver_prj.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_rx_ram_8_2048'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/OneDrive - HKUST Connect/Lab/OFDM_FPGA_VLC_Implementation/Receiver/prj/receiver_prj/receiver_prj.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
# IP: The module: 'udp_rx_ram_8_2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive - HKUST Connect/Lab/OFDM_FPGA_VLC_Implementation/Receiver/prj/receiver_prj/receiver_prj.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_rx_ram_8_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
